bbs/bbs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve
from bbs.settings import MEDIA_ROOT
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls','home'),namespace='home')),
    path('', include(('users.urls','users'),namespace='users')),
    #path(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT})
]

bbs/home/urls.py
#coding = utf-8
'''
    标题
    @name:
    @function:
    @author: Mr.Fan
    @date:2020--  
'''
from django.urls import path
from home.views import IndexView,ListView,PublishView,DetailView,ReplyView,QuoteView

urlpatterns = [
    #参数1:路由
    #参数2:视图函数名
    # path('hello/',HelloView.as_view()),
    #首页
    path('',IndexView.as_view(),name = 'index'),
    #列表页面
    path('list/',ListView.as_view(),name = 'list'),
    #发帖页面
    path('publish/',PublishView.as_view(),name = 'publish'),
    # 详情页面
    path('detail/<int:id>/',DetailView.as_view(),name = 'detail'),
    #评论页面
    path('reply/',ReplyView.as_view(),name = 'reply'),
    #回复功能
    path('quote/',QuoteView.as_view(),name = 'quote'),
]

bbs/users/urls.py
#coding = utf-8
'''
    标题
    @name:
    @function:
    @author: Mr.Fan
    @date:2020--  
'''
from django.urls import path

from users.views import RegisterView,LoginView,LogoutView

urlpatterns = [
    path('register/',RegisterView.as_view(),name = 'register'),
    path('login/',LoginView.as_view(),name = 'login'),
    path('logout/',LogoutView.as_view(),name = 'logout')
]

bbs/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>垃圾分类论坛_首页</title>
	<meta name="keywords" content="关键字列表" />
	<meta name="description" content="网页描述" />
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
	<style type="text/css"></style>
	<script type="text/javascript"></script>
</head>
<body>
	<div class="header_wrap">
		<div id="header" class="auto">
			<div class="logo">垃圾分类</div>
			<div class="nav">
				<a class="hover">首页</a>
			</div>
			<div class="serarch">
				<form>
					<input class="keyword" type="text" name="keyword" placeholder="搜索其实很简单" />
					<input class="submit" type="submit" name="submit" value="" />
				</form>
			</div>
            {% if is_login %}
                <div class="login">
                    <a href='#'>{{ name }}</a>&nbsp;
                    <a href='{% url 'users:logout' %}'>退出</a>
                </div>
            {% else %}
                <div class="login">
                    <a href='{% url 'users:login' %}'>登录</a>&nbsp;
                    <a href='{% url 'users:register' %}'>注册</a>
                </div>
            {% endif %}
		</div>
	</div>
	<div style="margin-top:55px;"></div>
	<div id="hot" class="auto">
		<div class="title">新闻消息</div>
		<ul class="newslist">
			<!-- 20条 -->
            {% for category in categories  %}
                <li>[<a href="{% url 'home:list' %}?cat_id={{ category.id }}">{{ category.name }}</a>] <a href="{% url 'home:list' %}?cat_id={{ category.id }}">{{ category.name }}</a></li>
            {% endfor %}

		</ul>
		<div style="clear:both;"></div>
	</div>
	<div class="box auto">
		<div class="title">
			跟帖
		</div>
		<div class="classList">
            {% for category in categories %}
                <div class="childBox new">
				<h2><a href="{% url 'home:list' %}?cat_id={{ category.id }}">{{ category.name }}</a> <span>(今日{{ category.today }})</span></h2>
				帖子：{{ category.total }}<br />
			</div>
            {% endfor %}

			<div style="clear:both;"></div>
		</div>
	</div>
	<div id="footer" class="auto">
		<div class="bottom">
			<a>垃圾分类</a>
		</div>
		<div class="copyright">Powered by qiruihua ©2019 </div>
	</div>
</body>
</html>

bbs/templates/list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>垃圾分类论坛_帖子列表页</title>
	<meta name="keywords" content="关键字列表" />
	<meta name="description" content="网页描述" />
    {% load static%}
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.pagination.css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
	<style type="text/css"></style>
	<script type="text/javascript"></script>
</head>
<body>
	<div class="header_wrap">
		<div id="header" class="auto">
			<div class="logo">垃圾分类</div>
			<div class="nav">
				<a class="hover" href="{% url 'home:index' %}">首页</a>
			</div>
			<div class="serarch">
				<form>
					<input class="keyword" type="text" name="keyword" placeholder="搜索其实很简单" />
					<input class="submit" type="submit" name="submit" value="" />
				</form>
			</div>
			{% if is_login %}
                <div class="login">
                    <a href='#'>{{ name }}</a>&nbsp;
                    <a href='{% url 'users:logout' %}'>退出</a>
                </div>
            {% else %}
                <div class="login">
                    <a href='{% url 'users:login' %}'>登录</a>&nbsp;
                    <a href='{% url 'users:register' %}'>注册</a>
                </div>
            {% endif %}
		</div>
	</div>
	<div style="margin-top:55px;"></div>
	<div id="position" class="auto">
		 <a href='{% url 'home:index' %}'>首页</a> &gt; <a href="{% url 'home:list' %}?cat_id={{ category.id }}">{{ category.name }}</a>
	</div>
	<div id="main" class="auto">
		<div id="left">
			<div class="box_wrap">
				<h3>{{ category.name }}</h3>
				<div class="num">
				    今日：<span>{{ today }}</span>&nbsp;&nbsp;&nbsp;
				    总帖：<span>{{ total }}</span>
				</div>
				<div class="pages_wrap">
					<a class="btn publish" href="{% url 'home:publish' %}?category.id={{ category.id }}"></a>
					<div style="clear:both;"></div>
				</div>
			</div>
			<div style="clear:both;"></div>
			<ul class="postsList">
				
				{% for article in articles %}
				    <li>
					<div class="smallPic">
						<a href="#">
							<img width="45" height="45" src="{% static 'image/2374101_small.jpg' %}/">
						</a>
					</div>
					<div class="subject">
						<div class="titleWrap"> &nbsp;&nbsp;<h2><a href="home:show">{{ article.title }}</a></h2></div>
						<p>
							楼主：{{ article.user.username }}&nbsp;{{ article.punlish_time }}&nbsp;&nbsp;&nbsp;最后回复：{{ article.last_comment_time }}
						</p>
					</div>
					<div class="count">
						<p>
							回复<br /><span>{{ article.comments }}</span>
						</p>
						<p>
							浏览<br /><span>{{ article.read_count }}</span>
						</p>
					</div>
					<div style="clear:both;"></div>
				</li>
				{% endfor %}





			</ul>
			<div class="pages_wrap">
				<a class="btn publish" href="{% url 'home:publish' %}"></a>
				<div class="pages">
					<div id="pagination" class="page"></div>
				</div>
				<div style="clear:both;"></div>
			</div>
		</div>
		<div id="right">
			<div class="classList">
				<div class="title">版块热门跟帖</div>
				<ul class="listWrap">
					<li>
						<ul>
                            {% for article in hot_articles  %}
                                <li><h3><a href="{% url 'home:detail' article.id %}">{{ article.title }}</a></h3></li>
                            {% endfor %}

						</ul>
					</li>
				</ul>
			</div>
		</div>
		<div style="clear:both;"></div>
	</div>
	<div id="footer" class="auto">
		<div class="bottom">
			<a>垃圾分类</a>
		</div>
		<div class="copyright">Powered by qiruihua ©2019 </div>
	</div>
</body>
</html>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage:{{ page_num }},
            totalPage: {{ total_page }},
            callback:function (current) {
                location.href = '?page=' + current;
            }
        })
    });
</script>

bbs/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>垃圾分类论坛_注册页</title>
	<meta name="keywords" content="关键字列表" />
	<meta name="description" content="网页描述" />
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
	<style type="text/css"></style>
	<script type="text/javascript"></script>
</head>
<body>
	<div class="header_wrap">
		<div id="header" class="auto">
			<div class="logo">垃圾分类</div>
			<div class="nav">
				<a class="hover" href="{% url 'home:index' %}">首页</a>
			</div>
			
			<div class="login">
				<a href='{% url 'users:login' %}'>登录</a>&nbsp;
				<a href='{% url 'users:register' %}'>注册</a>
			</div>
		</div>
	</div>
	<div style="margin-top:55px;"></div>
	<div id="login" class="auto">
		<h2>欢迎登陆论坛</h2>
		<form action="" method="POST">
            {% csrf_token %}
			<label>用户名：<input type="text" name="username"/><span></span></label>
			<label>密码：<input type="password"  name="password1"/><span></span></label>
			<input class="btn" type="submit" value="登陆" />
		</form>
	</div>
	<div id="footer" class="auto">
		<div class="bottom">
			<a>垃圾分类</a>
		</div>
		<div class="copyright">Powered by qiruihua ©2019 </div>
	</div>
</body>
</html>

bbs/templates/publish.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>垃圾分类论坛_发帖页</title>
	<meta name="keywords" content="关键字列表" />
	<meta name="description" content="网页描述" />
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/publish.css' %}" />
	<style type="text/css"></style>
	<script type="text/javascript"></script>
</head>
<body>
	<div class="header_wrap">
		<div id="header" class="auto">
			<div class="logo">垃圾分类</div>
			<div class="nav">
				<a class="hover" href="{% url 'home:index' %}">首页</a>
			</div>
			<div class="serarch">
				<form>
					<input class="keyword" type="text" name="keyword" placeholder="搜索其实很简单" />
					<input class="submit" type="submit" name="submit" value="" />
				</form>
			</div>
		    {% if is_login %}
                <div class="login">
                    <a href='#'>{{ name }}</a>&nbsp;
                    <a href='{% url 'users:logout' %}'>退出</a>
                </div>
            {% else %}
                <div class="login">
                    <a href='{% url 'users:login' %}'>登录</a>&nbsp;
                    <a href='{% url 'users:register' %}'>注册</a>
                </div>
            {% endif %}
		</div>
	</div>
	<div style="margin-top:55px;"></div>
	<div id="position" class="auto">
		 <a href='{% url 'home:index' %}'>首页</a> &gt; <a href="{% url 'home:list' %}?cat_id={{ category.id }}">{{ category.name }}</a>
	</div>
	<div id="publish">
		<form action="" method="post">
            {% csrf_token %}
			<select name="module_id">
				{% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
				{% endfor %}

			</select>
			<input class="title" placeholder="请输入标题" name="title" type="text" />
			<textarea name="content" class="content"></textarea>
			<input class="publish" type="submit" name="submit" value="" />
			<div style="clear:both;"></div>
		</form>
	</div>
	<div id="footer" class="auto">
		<div class="bottom">
			<a>垃圾分类</a>
		</div>
		<div class="copyright">Powered by qiruihua ©2019 </div>
	</div>
</body>
</html>

bbs/templates/quote.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>垃圾分类论坛_引用回复页</title>
	<meta name="keywords" content="关键字列表" />
	<meta name="description" content="网页描述" />
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/publish.css' %}" />
	<style type="text/css"></style>
	<script type="text/javascript"></script>
</head>
<body>
	<div class="header_wrap">
		<div id="header" class="auto">
			<div class="logo">垃圾分类</div>
			<div class="nav">
				<a class="hover" href="{% url 'home:index' %}">首页</a>
			</div>
			<div class="serarch">
				<form>
					<input class="keyword" type="text" name="keyword" placeholder="搜索其实很简单" />
					<input class="submit" type="submit" name="submit" value="" />
				</form>
			</div>
            {% if is_login %}
                <div class="login">
                    <a href='#'>{{ name }}</a>&nbsp;
                    <a href='{% url 'users:logout' %}'>退出</a>
                </div>
            {% else %}
                <div class="login">
                    <a href='{% url 'users:login' %}'>登录</a>&nbsp;
                    <a href='{% url 'users:register' %}'>注册</a>
                </div>
            {% endif %}
		</div>
	</div>
	<div style="margin-top:55px;"></div>
	<div id="position" class="auto">
		<a href='{% url 'home:index' %}'>首页</a> &gt; <a href="{% url 'home:list' comment.article.category.id %}">{{ category.name }}</a> &gt;
	</div>
	<div id="publish">
		<div>{{ comment.article.user.username }}: {{ comment.article.title }}</div>
		<div class="quote">
			<p class="title">引用 {{ comment.article.user.username }} 发表的: </p>
			{{ comment.content }}
		</div>
		<form method="post">
            {% csrf_token %}
			<textarea name="content" class="content"></textarea>
			<input class="reply" type="submit" name="submit" value="" />
			<div style="clear:both;"></div>
		</form>
	</div>
	<div id="footer" class="auto">
		<div class="bottom">
			<a>垃圾分类</a>
		</div>
		<div class="copyright">Powered by qiruihua ©2019</div>
	</div>
</body>
</html>

bbs/templates/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>垃圾分类论坛_注册页</title>
	<meta name="keywords" content="关键字列表" />
	<meta name="description" content="网页描述" />
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}" />
	<style type="text/css"></style>
	<script type="text/javascript"></script>
</head>
<body>
	<div class="header_wrap">
		<div id="header" class="auto">
			<div class="logo">垃圾分类</div>
			<div class="nav">
				<a class="hover" href="{% url 'home:index' %}">首页</a>
			</div>
			<div class="serarch">
				<form>
					<input class="keyword" type="text" name="keyword" placeholder="搜索其实很简单" />
					<input class="submit" type="submit" name="submit" value="" />
				</form>
			</div>
			<div class="login">
				<a href='{% url 'users:login' %}'>登录</a>&nbsp;
				<a href='{% url 'users:register' %}'>注册</a>
			</div>
		</div>
	</div>
	<div style="margin-top:55px;"></div>
	<div id="register" class="auto">
		<h2>欢迎注册成为论坛会员</h2>
		<form action="" method="POST">
            {% csrf_token %}
			<label>用户名：<input type="text" name="username"/><span>*6-10位，请使用英文字母、数字</span></label>
			<label>密码：<input type="password"  name="password1"/><span>*6-10位，请使用英文字母、数字，注意区分大小写</span></label>
			<label>确认密码：<input type="password" name="password2" /><span>*两次输入的密码必须一致</span></label>
			<label>验证码：<input name="vcode" type="text"  /><span>*请输入下方验证码</span></label>
			<img class="vcode" src="{% static 'image/show_code.jpg' %}" />
			<div style="clear:both;"></div>
			<input class="btn" type="submit" value="确定注册" />
		</form>
	</div>
	<div id="footer" class="auto">
		<div class="bottom">
			<a>垃圾分类</a>
		</div>
		<div class="copyright">Powered by qiruihua ©2019 </div>
	</div>
</body>
</html>

bbs/templates/reply.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>垃圾分类论坛_回复页面</title>
	<meta name="keywords" content="关键字列表" />
	<meta name="description" content="网页描述" />
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/publish.css' %}" />
	<style type="text/css"></style>
	<script type="text/javascript"></script>
</head>
<body>
	<div class="header_wrap">
		<div id="header" class="auto">
			<div class="logo">垃圾分类</div>
			<div class="nav">
				<a class="hover" href="{% url 'home:index' %}">首页</a>
			</div>
			<div class="serarch">
				<form>
					<input class="keyword" type="text" name="keyword" placeholder="搜索其实很简单" />
					<input class="submit" type="submit" name="submit" value="" />
				</form>
			</div>
			{% if is_login %}
                <div class="login">
                    <a href='#'>{{ name }}</a>&nbsp;
                    <a href='{% url 'users:logout' %}'>退出</a>
                </div>
            {% else %}
                <div class="login">
                    <a href='{% url 'users:login' %}'>登录</a>&nbsp;
                    <a href='{% url 'users:register' %}'>注册</a>
                </div>
            {% endif %}
		</div>
	</div>
	<div style="margin-top:55px;"></div>
	<div id="position" class="auto">
		 <a href='{% url 'home:index' %}'>首页</a> &gt; <a href='{% url 'home:reply' %}?article_id={{ article.id }}'>{{ article.category.name }}</a> &gt;{{ article.title }}
	</div>
	<div id="publish">
		<div>回复：由 {{ article.user.username }} 发布的  {{ article.title }}</div>
		<form method="post">
			<textarea name="content" class="content"></textarea>
			<input class="reply" type="submit" name="submit" value="" />
			<div style="clear:both;"></div>
		</form>
	</div>
	<div id="footer" class="auto">
		<div class="bottom">
			<a>垃圾分类</a>
		</div>
		<div class="copyright">Powered by qiruihua ©2019</div>
	</div>
</body>
</html>

bbs/templates/show.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>垃圾分类论坛_帖子详情页</title>
	<meta name="keywords" content="关键字列表" />
	<meta name="description" content="网页描述" />
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/show.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.pagination.css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
	<style type="text/css"></style>
	<script type="text/javascript"></script>
</head>
<body>
	<div class="header_wrap">
		<div id="header" class="auto">
			<div class="logo">垃圾分类</div>
			<div class="nav">
				<a class="hover" href="{% url 'home:index' %}">首页</a>
			</div>
			<div class="serarch">
				<form>

					<input class="keyword" type="text" name="keyword" placeholder="搜索其实很简单" />
					<input class="submit" type="submit" name="submit" value="" />
				</form>
			</div>
			<div class="login">
				{% if is_login %}
                    <div class="login">
                        <a href='#'>{{ name }}</a>&nbsp;
                        <a href='{% url 'users:logout' %}'>退出</a>
                    </div>
                {% else %}
                    <div class="login">
                        <a href='{% url 'users:login' %}'>登录</a>&nbsp;
                        <a href='{% url 'users:register' %}'>注册</a>
                    </div>
                {% endif %}
			</div>
		</div>
	</div>
	<div style="margin-top:55px;"></div>
	<div id="position" class="auto">
		 <a href='{% url 'home:index' %}'>首页</a> &gt; <a href="{% url 'home:list' %}?cat_id={{ category.id }}">{{ category.name }}</a> &gt;
	</div>
	<div id="main" class="auto">
		<div class="wrap1">
			<a class="btn reply" href="{% url 'home:reply' %}?article_id={{ article.id }}"></a>
			<div style="clear:both;"></div>
		</div>
		<div class="wrapContent">
			<div class="left">
				<div class="face">
					<a target="_blank" href="">
						<img src="{% static 'image/2374101_middle.jpg' %}" />
					</a>
				</div>
				<div class="name">
					<a href="">{{ article.user.name }}</a>
				</div>
			</div>
			<div class="right">
				<div class="title">
					<h2> {{ article.title }}</h2>
					<span>阅读：{{ article.read_count }}&nbsp;|&nbsp;回复：{{ article.comments }}</span>
					<div style="clear:both;"></div>
				</div>
				<div class="pubdate">
					<span class="date">发布于：{{ article.publish_time }} </span>
					<span class="floor" style="color:red;font-size:14px;font-weight:bold;">楼主</span>
				</div>
				<div class="content">
					  {{ article.content }}
				</div>
			</div>
			<div style="clear:both;"></div>
		</div>
        {% for comment in comments %}
            <div class="wrapContent">
			<div class="left">
				<div class="face">
					<a target="_blank" href="">
						<img src="{% static 'image/2374102_middle.jpg' %}" />
					</a>
				</div>
				<div class="name">
					<a href="">{{ comment.user.name }}</a>
				</div>
			</div>
			<div class="right">

				<div class="pubdate">
					<span class="date">回复时间：{{ comment.create_time }}</span>
					<span class="floor">{{ comment.floor }}楼&nbsp;|&nbsp;<a href="{% url 'home:quote' %}?comment_id={{ comment.id }}">引用</a></span>
				</div>
				<div class="content">
					{% if comment.parent_id %}
                        <div class="quote">
                        <h2>引用{{ comment.parent.user.username }}发表的:</h2>
                        {{ comment.parent.content }}
                        </div>
					{% endif %}
                    {{ comment.content }}
				</div>
			</div>
			<div style="clear:both;"></div>
		</div>
		<div class="wrapContent">
			<div class="left">
				<div class="face">
					<a target="_blank" data-uid="2374101" href="">
						<img src="{% static 'image/2374103_middle.jpg' %}" />
					</a>
				</div>
				<div class="name">
					<a class="J_user_card_show mr5" data-uid="2374101" href="">{{ comment.user.name }}</a>
				</div>
			</div>
        {% endfor %}

		<div class="wrap1">
				<div class="pages">
					<div id="pagination" class="page"></div>
				</div>
			<a class="btn reply" href="{% url 'home:reply' %}?article_id={{ article.id }}"></a>
			<div style="clear:both;"></div>
		</div>
	</div>
	<div id="footer" class="auto">
		<div class="bottom">
			<a>垃圾分类</a>
		</div>
		<div class="copyright">Powered by qiruihua ©2019 </div>
	</div>
</body>
</html>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage:{{ page_num }},
            totalPage: {{ total_page }},
            callback:function (current) {
                location.href = '?page=' + current;
            }
        })
    });
</script>